services:
  postgres:
    container_name: postgres-produits
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: produit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gestion-produits
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d scolaire-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  product-api:
    build: .
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres-produits
      - DB_PORT=5432
      - DB_NAME=produit_db
      - DB_USERNAME=username
      - DB_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - gestion-produits

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - gestion-produits
    depends_on:
      - postgres-sonar

  postgres-sonar:
    image: postgres
    container_name: postgres-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql_sonar:/var/lib/postgresql/data
    networks:
      - gestion-produits

  ###
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - gestion-produits
    user: root

networks:
  gestion-produits:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_sonar:

