services:
  postgres:
    container_name: postgres-produits
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: produit_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d scolaire-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  product-api:
    build: .
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres-produits
      - DB_PORT=5432
      - DB_NAME=produit_db
      - DB_USERNAME=username
      - DB_PASSWORD=password
    depends_on:
      - postgres