spring:
  application:
    name: gestion-produits
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:produit_db}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json

server:
  port: 8083

logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: logs/logs.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
